# Generated by Django 3.2.9 on 2021-12-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('community', models.CharField(max_length=50, null=True)),
                ('type_of_device', models.CharField(max_length=50)),
                ('type_of_monitoring', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=50)),
                ('if_alert', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNMP_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_packets', models.IntegerField()),
                ('out_packets', models.IntegerField()),
                ('bad_version', models.IntegerField()),
                ('bad_community', models.IntegerField()),
                ('in_getrequset', models.IntegerField()),
                ('in_getnext', models.IntegerField()),
                ('in_set', models.IntegerField()),
                ('in_response', models.IntegerField()),
                ('in_trap', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp', to='network_monitor.devices')),
            ],
        ),
        migrations.CreateModel(
            name='Ram_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ram', models.FloatField()),
                ('available_space', models.FloatField()),
                ('percent_of_used', models.FloatField()),
                ('used_space', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='network_monitor.devices')),
            ],
        ),
        migrations.CreateModel(
            name='Network_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_name', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=50)),
                ('ip4', models.CharField(max_length=50)),
                ('subnet', models.CharField(max_length=50)),
                ('ip6', models.CharField(max_length=50)),
                ('is_up', models.BooleanField()),
                ('network_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='network_monitor.devices')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_utilization', models.IntegerField()),
                ('used_memory', models.FloatField()),
                ('free_memory', models.FloatField()),
                ('total_memory', models.FloatField()),
                ('temp_status', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='network_monitor.devices')),
            ],
        ),
        migrations.CreateModel(
            name='Get_Interfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=50)),
                ('interface_status', models.CharField(max_length=50)),
                ('interface_oid_number', models.IntegerField()),
                ('interfaces_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='network_monitor.devices')),
            ],
        ),
        migrations.CreateModel(
            name='General_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50)),
                ('num_of_interfaces', models.IntegerField()),
                ('uptime', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general', to='network_monitor.devices')),
            ],
        ),
        migrations.CreateModel(
            name='Disk_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_name', models.CharField(max_length=50)),
                ('disk_type', models.CharField(max_length=50)),
                ('disk_size', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('disk_percent_used', models.FloatField()),
                ('disk_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='network_monitor.devices')),
            ],
        ),
        migrations.CreateModel(
            name='Cpu_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_of_cpu', models.FloatField()),
                ('user_mode', models.FloatField()),
                ('system_mode', models.FloatField()),
                ('idle', models.FloatField()),
                ('interrupt', models.FloatField()),
                ('number_of_cores', models.IntegerField()),
                ('number_of_logical', models.IntegerField()),
                ('current_freq', models.FloatField()),
                ('min_freq', models.FloatField()),
                ('max_freq', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='network_monitor.devices')),
            ],
        ),
    ]
